clc;
clearvars;
close all;

% Draw cached EA and ROI statistics without rereading the raw MAT files.

scriptDir = fileparts(mfilename("fullpath"));
if strlength(scriptDir) == 0
    scriptDir = pwd;
end

dataFile = fullfile(scriptDir, "advantage.mat");
if ~isfile(dataFile)
    error("Processed data not found. Run advantage_data.m first: %s", ...
        dataFile);
end

variableNames = [ ...
    "spotDetectionRangeMean", "lineDetectionRangeMean", ...
    "annularDetectionRangeMean", "roiRaSpotDetectionRangeMean", ...
    "roiRaLineDetectionRangeMean", "roiRaAnnularDetectionRangeMean", ...
    "roiSpSpotDetectionRangeMean", "roiSpLineDetectionRangeMean", ...
    "roiSpAnnularDetectionRangeMean", ...
    "spotEffectivePulseCountMean", ...
    "spotEffectivePulseClusterCountMean", ...
    "lineEffectivePulseCountMean", ...
    "lineEffectivePulseClusterCountMean", ...
    "annularEffectivePulseCountMean", ...
    "annularEffectivePulseClusterCountMean", ...
    "roiRaSpotEffectivePulseCountMean", ...
    "roiRaSpotEffectivePulseClusterCountMean", ...
    "roiRaLineEffectivePulseCountMean", ...
    "roiRaLineEffectivePulseClusterCountMean", ...
    "roiRaAnnularEffectivePulseCountMean", ...
    "roiRaAnnularEffectivePulseClusterCountMean", ...
    "roiSpSpotEffectivePulseCountMean", ...
    "roiSpSpotEffectivePulseClusterCountMean", ...
    "roiSpLineEffectivePulseCountMean", ...
    "roiSpLineEffectivePulseClusterCountMean", ...
    "roiSpAnnularEffectivePulseCountMean", ...
    "roiSpAnnularEffectivePulseClusterCountMean"];
data = load(dataFile, variableNames{:});
validateProcessedData(data, variableNames, dataFile);

numberOfDiameters = numel(data.spotEffectivePulseCountMean);
wDMrad = (5:5:(5 * numberOfDiameters)).';

effectivePulseCountMean = cat(3, ...
    [data.spotEffectivePulseCountMean, ...
     data.lineEffectivePulseCountMean, ...
     data.annularEffectivePulseCountMean], ...
    [data.roiRaSpotEffectivePulseCountMean, ...
     data.roiRaLineEffectivePulseCountMean, ...
     data.roiRaAnnularEffectivePulseCountMean], ...
    [data.roiSpSpotEffectivePulseCountMean, ...
     data.roiSpLineEffectivePulseCountMean, ...
     data.roiSpAnnularEffectivePulseCountMean]);

effectivePulseClusterCountMean = cat(3, ...
    [data.spotEffectivePulseClusterCountMean, ...
     data.lineEffectivePulseClusterCountMean, ...
     data.annularEffectivePulseClusterCountMean], ...
    [data.roiRaSpotEffectivePulseClusterCountMean, ...
     data.roiRaLineEffectivePulseClusterCountMean, ...
     data.roiRaAnnularEffectivePulseClusterCountMean], ...
    [data.roiSpSpotEffectivePulseClusterCountMean, ...
     data.roiSpLineEffectivePulseClusterCountMean, ...
     data.roiSpAnnularEffectivePulseClusterCountMean]);

beamLabels = ["Spot", "Line", "Annular"];
detectionRangeMean = cat(3, ...
    [data.spotDetectionRangeMean, data.lineDetectionRangeMean, ...
     data.annularDetectionRangeMean], ...
    [data.roiRaSpotDetectionRangeMean, data.roiRaLineDetectionRangeMean, ...
     data.roiRaAnnularDetectionRangeMean], ...
    [data.roiSpSpotDetectionRangeMean, data.roiSpLineDetectionRangeMean, ...
     data.roiSpAnnularDetectionRangeMean]);
columnTitles = ["ROE", "ROI-RA", "ROI-SP"];
% Analytic population means of the configured initial-position sampling:
% ROE: r0 = 2000 m. ROI: r0^2 ~ U(100^2, 2000^2), hence
% E[r0] = (2/3)*(2000^3-100^3)/(2000^2-100^2) = 1336.507936508 m.
% These references describe ALL initial trials, not the detected subset.
initialRangeReference = [2000, 1336.507936508, 1336.507936508];
colors = [ ...
    0.4660, 0.6740, 0.1880; ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980];

figureHandle = figure("Color", "w", "Position", [100, 50, 800, 600]);
layout = tiledlayout(figureHandle, 3, 3, ...
    "TileSpacing", "compact", "Padding", "compact");

axesHandles = gobjects(3, 3);
rowData = {detectionRangeMean, effectivePulseCountMean, ...
    effectivePulseClusterCountMean};
rowLabels = ["Detection range (m)", "Pulse count", ...
    "Pulse cluster"];
legendLines = gobjects(1, numel(beamLabels));
for rowIndex = 1:3
    for columnIndex = 1:3
        axesHandle = nexttile(layout, (rowIndex - 1) * 3 + columnIndex);
        axesHandles(rowIndex, columnIndex) = axesHandle;
        axesHandle.Toolbar.Visible = "off";
        panelTitle = "";
        xLabelText = "";
        if rowIndex == 1
            panelTitle = columnTitles(columnIndex);
        elseif rowIndex == 3
            xLabelText = "{\it w}_{\rmD} (mrad)";
        end
        formatCountAxes(axesHandle, panelTitle, xLabelText);
        hold(axesHandle, "on");
        for beamIndex = 1:numel(beamLabels)
            lineHandle = plot(axesHandle, wDMrad, ...
                rowData{rowIndex}(:, beamIndex, columnIndex), "-", ...
                "LineWidth", 3, "Color", colors(beamIndex, :), ...
                "DisplayName", beamLabels(beamIndex));
            if rowIndex == 1 && columnIndex == 1
                legendLines(beamIndex) = lineHandle;
            end
        end
        switch rowIndex
            case 1
                if columnIndex == 1
                    ylim(axesHandle, [0, 2400]);
                    yticks(axesHandle, 0:800:2400);
                else
                    ylim(axesHandle, [0, 2400]);
                    yticks(axesHandle, 0:800:2400);
                end
                yline(axesHandle, initialRangeReference(columnIndex), ":", ...
                    "Color", [0.45, 0.45, 0.45], "LineWidth", 3, ...
                    "HandleVisibility", "off");
                rangeLabelY = mean([initialRangeReference(columnIndex), ...
                    axesHandle.YLim(2)]);
                % text(axesHandle, 12, rangeLabelY, sprintf( ...
                %     'Mean initial range: %.0f m', ...
                %     initialRangeReference(columnIndex)), ...
                %     "FontName", "Helvetica", "FontSize", 12, ...
                %     "Color", [0.3, 0.3, 0.3], "VerticalAlignment", "middle");
                set(axesHandle, "FontName", "Helvetica");
                set([axesHandle.Title, axesHandle.XLabel, axesHandle.YLabel], ...
                    "FontName", "Helvetica");
            case 2
                set(axesHandle, "YScale", "log");
                ylim(axesHandle, [1, 1000]);
                yticks(axesHandle, 10.^(0:3));
                set(axesHandle, "YGrid", "on", "YMinorGrid", "off");
            case 3
                ylim(axesHandle, [1, 2]);
                yticks(axesHandle, 1:0.25:2);
        end
        if columnIndex == 1
            ylabel(axesHandle, rowLabels(rowIndex));
        else
            ylabel(axesHandle, "");
            yticklabels(axesHandle, {});
        end
        % Share labels along rows/columns while retaining ticks and grids.
        if rowIndex < 3
            xlabel(axesHandle, "");
            xticklabels(axesHandle, {});
        end
    end
end

legendHandle = legend(axesHandles(1, 1), legendLines, beamLabels, ...
    "Location", "best", "FontName", "Helvetica", "FontSize", 14);
legendHandle.Layout.Tile = "north";
legendHandle.NumColumns = numel(beamLabels);
legendHandle.Box = "off";
legendHandle.ItemTokenSize = [50, 18];

drawnow;
exportgraphics(figureHandle, fullfile(scriptDir, "advantage.png"), ...
    "Resolution", 300);

function validateProcessedData(data, variableNames, dataFile)
    missingVariables = variableNames(~isfield(data, variableNames));
    if ~isempty(missingVariables)
        error("Missing variables in %s: %s", ...
            dataFile, strjoin(missingVariables, ", "));
    end

    expectedLength = numel(data.(variableNames(1)));
    for variableIndex = 1:numel(variableNames)
        variableName = variableNames(variableIndex);
        values = data.(variableName);
        if ~isa(values, "double") || ~iscolumn(values) || ...
                numel(values) ~= expectedLength
            error("%s in %s must be an N-by-1 double array, with the same " + ...
                "N as the other variables.", variableName, dataFile);
        end
    end
end

function formatCountAxes(axesHandle, panelTitle, xLabelText)
    grid(axesHandle, "on");
    box(axesHandle, "on");
    xlim(axesHandle, [0, 400]);
    xticks(axesHandle, 0:100:400);
    xtickangle(axesHandle, 0);
    title(axesHandle, panelTitle, "Interpreter", "none", ...
        "FontName", "Helvetica", "FontSize", 14, "FontWeight", "normal");
    xlabel(axesHandle, xLabelText, "Interpreter", "tex");
    set(axesHandle, "FontName", "Helvetica", "FontSize", 14, ...
        "TitleFontSizeMultiplier", 1, "TitleFontWeight", "normal", ...
        "LineWidth", 2, "XScale", "linear");
    set(axesHandle.Title, "FontSize", 14, "FontWeight", "normal");
    set([axesHandle.XLabel, axesHandle.YLabel], ...
        "FontName", "Helvetica", "FontSize", 14);
end
