function window_photons = empty_detection_window_photons()
%EMPTY_DETECTION_WINDOW_PHOTONS Canonical empty fourth-output value.
% Photon counts remain double because they are expected photon counts and
% are generally fractional. Pulse indices are uint32 to reduce file size.

window_photons = struct( ...
    'signal_photons', zeros(0, 1), ...
    'backscatter_photons', zeros(0, 1), ...
    'background_photons', nan, ...
    'dark_count_photons', nan, ...
    'pulse_steps', zeros(0, 1, 'uint32'));
end
