function result = iso_performance_snr_analysis(outputDir, resultDir, exportOutputs)
%ISO_PERFORMANCE_SNR_ANALYSIS Compare iso-performance annular and line beams.
%
% result = iso_performance_snr_analysis()
% result = iso_performance_snr_analysis(outputDir, resultDir, exportOutputs)
%
% The analysis uses the ROE operating points identified in the paper:
%   annular beam: w_D = 120 mrad
%   line beam:    w_D = 195 mrad
% Both use w_d = 1 mrad and the baseline parameters from Table 1.  The
% single-pulse photon model and 7-by-7 finite-target averaging follow the
% definitions in MC_ring_snr.m and MC_line_snr.m.  Existing 50,000-trial
% Monte Carlo files provide detection probability, warning time, and the
% effective-pulse-count distribution; the full MC sweep is not rerun.

scriptDir = fileparts(mfilename("fullpath"));
if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(scriptDir, "iso_performance_snr_results");
end
if nargin < 2 || isempty(resultDir)
    resultDir = fullfile(fileparts(fileparts(scriptDir)), "MC_RESULTS");
end
if nargin < 3 || isempty(exportOutputs)
    exportOutputs = true;
end

outputDir = char(outputDir);
resultDir = char(resultDir);
exportOutputs = logical(exportOutputs);

parameters = baseline_parameters();
rangeM = (500:10:2000).';

annular = calculate_annular_budget(rangeM, parameters);
lineBeam = calculate_line_budget(rangeM, parameters);
mc = load_iso_performance_mc(resultDir);

effectivePulseN = (1:max([mc.annular.effectivePulses; ...
    mc.line.effectivePulses])).';
annularCCDF = arrayfun(@(n) mean(mc.annular.effectivePulses >= n), ...
    effectivePulseN);
lineCCDF = arrayfun(@(n) mean(mc.line.effectivePulses >= n), ...
    effectivePulseN);

photonTable = table(rangeM, annular.illuminationFactor, ...
    lineBeam.illuminationFactor, annular.signalPhotons, ...
    lineBeam.signalPhotons, annular.backgroundPhotons, ...
    lineBeam.backgroundPhotons, annular.backscatterPhotons, ...
    lineBeam.backscatterPhotons, annular.darkPhotons, ...
    lineBeam.darkPhotons, annular.noisePhotons, lineBeam.noisePhotons, ...
    annular.snr, lineBeam.snr, annular.snr ./ lineBeam.snr, ...
    'VariableNames', { ...
    'Range_m', 'AnnularIlluminationFactor', 'LineIlluminationFactor', ...
    'AnnularSignalPhotons', 'LineSignalPhotons', ...
    'AnnularBackgroundPhotons', 'LineBackgroundPhotons', ...
    'AnnularBackscatterPhotons', 'LineBackscatterPhotons', ...
    'AnnularDarkPhotons', 'LineDarkPhotons', ...
    'AnnularNoisePhotons', 'LineNoisePhotons', ...
    'AnnularSNR', 'LineSNR', 'SNRRatioAnnularToLine'});

summaryTable = table( ...
    ["Annular"; "Line"], ...
    1e3 .* [parameters.annularWD; parameters.lineWD], ...
    [mc.annular.detectionProbability; mc.line.detectionProbability], ...
    [mc.annular.meanWarningTime; mc.line.meanWarningTime], ...
    [mc.annular.meanEffectivePulses; mc.line.meanEffectivePulses], ...
    [mc.annular.medianEffectivePulses; mc.line.medianEffectivePulses], ...
    [mc.annular.p95EffectivePulses; mc.line.p95EffectivePulses], ...
    'VariableNames', {'Beam', 'wD_mrad', 'DetectionProbability', ...
    'MeanWarningTime_s', 'MeanEffectivePulses', ...
    'MedianEffectivePulses', 'P95EffectivePulses'});

effectivePulseTable = table(effectivePulseN, annularCCDF, lineCCDF, ...
    'VariableNames', {'EffectivePulseThreshold', ...
    'AnnularProbabilityAtLeastN', 'LineProbabilityAtLeastN'});

referenceRanges = [500; 1000; 1500; 2000];
referenceAnnularSNR = interp1(rangeM, annular.snr, referenceRanges);
referenceLineSNR = interp1(rangeM, lineBeam.snr, referenceRanges);
referenceTable = table(referenceRanges, referenceAnnularSNR, ...
    referenceLineSNR, referenceAnnularSNR ./ referenceLineSNR, ...
    'VariableNames', {'Range_m', 'AnnularSNR', 'LineSNR', ...
    'SNRRatioAnnularToLine'});

metrics = struct( ...
    'wDReductionFraction', 1 - parameters.annularWD / parameters.lineWD, ...
    'outerFieldReductionFraction', 1 - annular.outerFieldAngle / ...
        lineBeam.outerFieldAngle, ...
    'fovSolidAngleRatio', annular.fovSolidAngle / lineBeam.fovSolidAngle, ...
    'beamSolidAngleRatio', annular.beamSolidAngle / lineBeam.beamSolidAngle, ...
    'probabilityAtLeastTwoPulsesAnnular', annularCCDF(2), ...
    'probabilityAtLeastTwoPulsesLine', lineCCDF(2));

result = struct( ...
    'parameters', parameters, ...
    'annular', annular, ...
    'line', lineBeam, ...
    'mc', mc, ...
    'photonTable', photonTable, ...
    'summaryTable', summaryTable, ...
    'effectivePulseTable', effectivePulseTable, ...
    'referenceTable', referenceTable, ...
    'metrics', metrics);

if exportOutputs
    export_analysis(result, outputDir);
    print_summary(result, outputDir);
end
end

function parameters = baseline_parameters()
parameters = struct( ...
    'annularWD', 120e-3, ...
    'lineWD', 195e-3, ...
    'wSmall', 1e-3, ...
    'wavelength', 1550e-9, ...
    'pulseEnergy', 150e-6, ...
    'receiverDiameter', 0.0508, ...
    'opticalEfficiency', 0.80, ...
    'detectorEfficiency', 0.80, ...
    'timeGate', 50e-9, ...
    'extinctionCoefficient', 1.5e-5, ...
    'backscatterCoefficient', 0.3e-6, ...
    'skyRadiancePerNm', 5e-9, ...
    'filterBandwidthNm', 10.0, ...
    'darkCountRate', 400, ...
    'targetWidth', 0.297, ...
    'targetReflectivity', 0.5, ...
    'mcColumn', 1);
end

function budget = calculate_annular_budget(rangeM, parameters)
ringRadius = parameters.annularWD / 2;
gaussianWidth = parameters.wSmall / 2;
beamSolidAngle = annular_gaussian_solid_angle(ringRadius, gaussianWidth);
fovHalfWidth = 3 * parameters.wSmall;
fovInner = max(ringRadius - fovHalfWidth, 0);
fovOuter = min(ringRadius + fovHalfWidth, pi);
fovSolidAngle = 2 * pi * (cos(fovInner) - cos(fovOuter));
illuminationFactor = annular_peak_target_factor(rangeM, ...
    parameters.targetWidth, ringRadius, gaussianWidth);

budget = calculate_common_budget(rangeM, parameters, beamSolidAngle, ...
    fovSolidAngle, illuminationFactor);
budget.outerFieldAngle = fovOuter;
budget.beamSolidAngle = beamSolidAngle;
budget.fovSolidAngle = fovSolidAngle;
end

function budget = calculate_line_budget(rangeM, parameters)
longHalfWidth = parameters.lineWD / 2;
gaussianWidth = parameters.wSmall / 2;
beamSolidAngle = parameters.lineWD * gaussianWidth * sqrt(pi / 2);
fovSolidAngle = parameters.lineWD * (6 * parameters.wSmall);
illuminationFactor = line_peak_target_factor(rangeM, ...
    parameters.targetWidth, longHalfWidth, gaussianWidth);

budget = calculate_common_budget(rangeM, parameters, beamSolidAngle, ...
    fovSolidAngle, illuminationFactor);
budget.outerFieldAngle = parameters.lineWD / 2 + 3 * parameters.wSmall;
budget.beamSolidAngle = beamSolidAngle;
budget.fovSolidAngle = fovSolidAngle;
end

function budget = calculate_common_budget(rangeM, parameters, ...
        beamSolidAngle, fovSolidAngle, illuminationFactor)
h = 6.62607015e-34;
c = 299792458;
photonEnergy = h * c / parameters.wavelength;
transmittedPhotons = parameters.pulseEnergy / photonEnergy;
receiverArea = pi * (parameters.receiverDiameter / 2)^2;
systemEfficiency = parameters.opticalEfficiency * ...
    parameters.detectorEfficiency;
targetArea = parameters.targetWidth^2;

twoWayTransmission = exp(-2 * parameters.extinctionCoefficient .* rangeM);
beamArea = beamSolidAngle .* rangeM.^2;
signalPhotons = transmittedPhotons .* ...
    (targetArea .* illuminationFactor ./ beamArea) .* ...
    parameters.targetReflectivity .* ...
    (receiverArea ./ (pi .* rangeM.^2)) .* ...
    twoWayTransmission .* systemEfficiency;

backgroundPhotons = parameters.skyRadiancePerNm * ...
    parameters.filterBandwidthNm * receiverArea * fovSolidAngle * ...
    parameters.timeGate * systemEfficiency / photonEnergy;
backgroundPhotons = repmat(backgroundPhotons, size(rangeM));
darkPhotons = repmat(parameters.darkCountRate * parameters.timeGate, ...
    size(rangeM));
backscatterPhotons = calculate_backscatter_photons(transmittedPhotons, ...
    systemEfficiency, receiverArea, parameters.backscatterCoefficient, ...
    parameters.extinctionCoefficient, rangeM, parameters.timeGate, c);
noisePhotons = backscatterPhotons + backgroundPhotons + darkPhotons;
snr = signalPhotons ./ sqrt(signalPhotons + noisePhotons);

budget = struct( ...
    'rangeM', rangeM, ...
    'illuminationFactor', illuminationFactor, ...
    'signalPhotons', signalPhotons, ...
    'backgroundPhotons', backgroundPhotons, ...
    'backscatterPhotons', backscatterPhotons, ...
    'darkPhotons', darkPhotons, ...
    'noisePhotons', noisePhotons, ...
    'snr', snr);
end

function factor = line_peak_target_factor(rangeM, targetWidth, ...
        longHalfWidth, gaussianWidth)
gridN = 7;
nodes = ((1:gridN) - 0.5) ./ gridN - 0.5;
[sampleLong, sampleShort] = meshgrid(nodes, nodes);
sampleLong = sampleLong(:).';
sampleShort = sampleShort(:).';

angularSide = 2 .* atan((targetWidth / 2) ./ rangeM);
sampleL = angularSide .* sampleLong;
sampleS = angularSide .* sampleShort;
insideLong = abs(sampleL) <= longHalfWidth;
sampleIntensity = insideLong .* exp(-2 .* (sampleS ./ gaussianWidth).^2);
factor = mean(sampleIntensity, 2);
end

function factor = annular_peak_target_factor(rangeM, targetWidth, ...
        ringRadius, gaussianWidth)
gridN = 7;
nodes = ((1:gridN) - 0.5) ./ gridN - 0.5;
[sampleX, sampleY] = meshgrid(nodes, nodes);
sampleX = sampleX(:).';
sampleY = sampleY(:).';

angularSide = 2 .* atan((targetWidth / 2) ./ rangeM);
dx = angularSide .* sampleX;
dy = angularSide .* sampleY;
sampleTheta = sqrt((ringRadius + dx).^2 + dy.^2);
sampleIntensity = exp(-2 .* ((sampleTheta - ringRadius) ./ gaussianWidth).^2);
factor = mean(sampleIntensity, 2);
end

function solidAngle = annular_gaussian_solid_angle(ringRadius, gaussianWidth)
u0 = -sqrt(2) * ringRadius / gaussianWidth;
radialIntegral = ringRadius * gaussianWidth * sqrt(pi) / ...
    (2 * sqrt(2)) * erfc(u0) + gaussianWidth^2 / 4 * ...
    exp(-2 * (ringRadius / gaussianWidth)^2);
solidAngle = 2 * pi * radialIntegral;
end

function photons = calculate_backscatter_photons(transmittedPhotons, ...
        systemEfficiency, receiverArea, beta, alpha, rangeM, timeGate, c)
rangeBinLength = c * timeGate / 2;
offsets = linspace(-rangeBinLength / 2, rangeBinLength / 2, 101);
rangeGrid = rangeM + offsets;
rangeGrid(rangeGrid <= 0) = 1e-6;
integrand = beta .* exp(-2 .* alpha .* rangeGrid) ./ rangeGrid.^2;
rangeIntegral = trapz(offsets, integrand, 2);
photons = transmittedPhotons * systemEfficiency * receiverArea .* ...
    rangeIntegral;
end

function mc = load_iso_performance_mc(resultDir)
annularFile = fullfile(resultDir, ...
    'MC_1par_EA_RING_D120d1mrad.mat');
lineFile = fullfile(resultDir, ...
    'MC_1par_EA_LINE_D195d1mrad.mat');
if ~isfile(annularFile)
    error('isoPerformanceSNR:MissingAnnularData', ...
        'Annular Monte Carlo file not found: %s', annularFile);
end
if ~isfile(lineFile)
    error('isoPerformanceSNR:MissingLineData', ...
        'Line Monte Carlo file not found: %s', lineFile);
end

annularData = load(annularFile, 'detect_R', 'first_time_R', ...
    'effective_pulses_R');
lineData = load(lineFile, 'detect_L', 'first_time_L', ...
    'effective_pulses_L');
column = 1;

annularDetected = annularData.detect_R(:, column) ~= 0;
lineDetected = lineData.detect_L(:, column) ~= 0;
annularEffective = annularData.effective_pulses_R(annularDetected, column);
lineEffective = lineData.effective_pulses_L(lineDetected, column);
annularEffective = annularEffective(isfinite(annularEffective));
lineEffective = lineEffective(isfinite(lineEffective));

mc = struct;
mc.annular = summarize_mc(annularDetected, ...
    annularData.first_time_R(:, column), annularEffective, annularFile);
mc.line = summarize_mc(lineDetected, ...
    lineData.first_time_L(:, column), lineEffective, lineFile);
end

function summary = summarize_mc(detected, warningTime, effectivePulses, sourceFile)
validWarning = detected & isfinite(warningTime);
summary = struct( ...
    'sourceFile', sourceFile, ...
    'trialCount', numel(detected), ...
    'detectionProbability', mean(detected), ...
    'meanWarningTime', mean(warningTime(validWarning)), ...
    'effectivePulses', effectivePulses, ...
    'meanEffectivePulses', mean(effectivePulses), ...
    'medianEffectivePulses', median(effectivePulses), ...
    'p95EffectivePulses', prctile(effectivePulses, 95));
end

function export_analysis(result, outputDir)
if ~isfolder(outputDir)
    mkdir(outputDir);
end

writetable(result.photonTable, fullfile(outputDir, ...
    'iso_performance_snr_photon_budget.csv'));
writetable(result.summaryTable, fullfile(outputDir, ...
    'iso_performance_snr_summary.csv'));
writetable(result.effectivePulseTable, fullfile(outputDir, ...
    'iso_performance_snr_effective_pulses.csv'));
writetable(result.referenceTable, fullfile(outputDir, ...
    'iso_performance_snr_reference_ranges.csv'));
save(fullfile(outputDir, 'iso_performance_snr_results.mat'), 'result');

figureHandle = create_summary_figure(result);
exportgraphics(figureHandle, fullfile(outputDir, ...
    'iso_performance_snr.png'), 'Resolution', 300);
savefig(figureHandle, fullfile(outputDir, 'iso_performance_snr.fig'));
close(figureHandle);
end

function figureHandle = create_summary_figure(result)
lineColor = [0.0000, 0.4470, 0.7410];
annularColor = [0.8500, 0.3250, 0.0980];

figureHandle = figure('Color', 'w', 'Position', [100, 100, 620, 900], ...
    'Visible', 'off');
layout = tiledlayout(figureHandle, 2, 1, ...
    'TileSpacing', 'compact', 'Padding', 'loose');

snrAxes = nexttile(layout, 1);
hold(snrAxes, 'on');
plot(snrAxes, result.line.rangeM, result.line.snr, '-', ...
    'Color', lineColor, 'LineWidth', 2.2, 'DisplayName', ...
    'Line, w_D=195 mrad');
plot(snrAxes, result.annular.rangeM, result.annular.snr, '-', ...
    'Color', annularColor, 'LineWidth', 2.2, 'DisplayName', ...
    'Annular, w_D=120 mrad');
yline(snrAxes, 2, '--', 'SNR threshold', 'Color', [0.25, 0.25, 0.25], ...
    'LineWidth', 1.2, 'LabelHorizontalAlignment', 'left', ...
    'HandleVisibility', 'off');
xlabel(snrAxes, 'Range (m)');
ylabel(snrAxes, 'Peak-hit single-pulse SNR');
title(snrAxes, '(a) Photon-level detectability', 'FontWeight', 'normal');
legend(snrAxes, 'Location', 'northeast', 'Box', 'off');
grid(snrAxes, 'on');
box(snrAxes, 'on');

pulseAxes = nexttile(layout, 2);
hold(pulseAxes, 'on');
set(pulseAxes, 'YScale', 'log');
lineCCDF = result.effectivePulseTable.LineProbabilityAtLeastN;
annularCCDF = result.effectivePulseTable.AnnularProbabilityAtLeastN;
lineCCDF(lineCCDF == 0) = nan;
annularCCDF(annularCCDF == 0) = nan;
semilogy(pulseAxes, ...
    result.effectivePulseTable.EffectivePulseThreshold, lineCCDF, '-s', ...
    'Color', lineColor, 'LineWidth', 2.0, 'MarkerSize', 5, ...
    'DisplayName', sprintf('Line, mean %.3f', ...
    result.mc.line.meanEffectivePulses));
semilogy(pulseAxes, ...
    result.effectivePulseTable.EffectivePulseThreshold, annularCCDF, '-o', ...
    'Color', annularColor, 'LineWidth', 2.0, 'MarkerSize', 5, ...
    'DisplayName', sprintf('Annular, mean %.3f', ...
    result.mc.annular.meanEffectivePulses));
xlabel(pulseAxes, 'Effective pulse threshold, n');
ylabel(pulseAxes, 'Conditional CCDF');
title(pulseAxes, '(b) Effective-pulse utilization', 'FontWeight', 'normal');
xlim(pulseAxes, [1, max(result.effectivePulseTable.EffectivePulseThreshold)]);
ylim(pulseAxes, [1e-5, 1]);
xticks(pulseAxes, result.effectivePulseTable.EffectivePulseThreshold);
yticks(pulseAxes, [1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1]);
yticklabels(pulseAxes, {'10^{-5}', '10^{-4}', '10^{-3}', ...
    '10^{-2}', '10^{-1}', '10^{0}'});
legend(pulseAxes, 'Location', 'northeast', 'Box', 'off');
grid(pulseAxes, 'on');
pulseAxes.YMinorGrid = 'off';
pulseAxes.XMinorGrid = 'off';
box(pulseAxes, 'on');

allAxes = [snrAxes, pulseAxes];
set(allAxes, 'FontName', 'Helvetica', 'FontSize', 11, 'LineWidth', 1.3);
end

function print_summary(result, outputDir)
fprintf('\nIso-performance annular-versus-line analysis\n');
fprintf('w_D reduction: %.2f %%\n', ...
    100 * result.metrics.wDReductionFraction);
fprintf('Maximum off-axis field reduction: %.2f %%\n', ...
    100 * result.metrics.outerFieldReductionFraction);
fprintf('Matched-FOV solid-angle ratio (annular/line): %.4f\n', ...
    result.metrics.fovSolidAngleRatio);
disp(result.summaryTable);
disp(result.referenceTable);
fprintf('P(N_eff >= 2 | detection): annular %.4f, line %.4f\n', ...
    result.metrics.probabilityAtLeastTwoPulsesAnnular, ...
    result.metrics.probabilityAtLeastTwoPulsesLine);
fprintf('Outputs saved to: %s\n', outputDir);
end
