function block_size = mc_ea_block_size(fasan_D, beam_type)
%MC_EA_BLOCK_SIZE Select the measured pulse block size for MC_EA.
%   BLOCK_SIZE = MC_EA_BLOCK_SIZE(FASAN_D, BEAM_TYPE) maps the full
%   divergence angle (radians) and beam type to the fastest measured
%   block-size region on this machine for N = 50000.
%
%   The one-input form retains the previous common policy for callers that
%   have not been benchmarked separately by beam type.

validateattributes(fasan_D, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'}, mfilename, 'fasan_D');

if nargin < 2 || isempty(beam_type)
    if fasan_D <= 5e-3
        block_size = 200000;
    elseif fasan_D <= 25e-3
        block_size = 100000;
    elseif fasan_D <= 40e-3
        block_size = 50000;
    else
        block_size = 20000;
    end
    return;
end

beam_type = validatestring(beam_type, {'ring', 'line', 'point'}, ...
    mfilename, 'beam_type');
% Round only for region selection so values generated by a 5 mrad colon
% expression land on the intended inclusive boundary despite roundoff.
fasan_D_mrad = round(fasan_D * 1e3, 9);

switch beam_type
    case 'ring'
        if fasan_D_mrad <= 10
            block_size = 240000;
        else
            block_size = 120000;
        end
    case 'line'
        if fasan_D_mrad <= 5
            block_size = 320000;
        elseif fasan_D_mrad <= 35
            block_size = 160000;
        else
            block_size = 80000;
        end
    case 'point'
        if fasan_D_mrad <= 10
            block_size = 240000;
        elseif fasan_D_mrad <= 125
            block_size = 120000;
        else
            block_size = 280000;
        end
end
end
