function [detect, first_detect, first_encounter, effective_pulses] = ...
    MC_line_SP_snr_NEW(fasan_D, fasan_d, ...
    line_scan, f, omiga, UP, UV, init_beam_idx, R, jiaodu)
%MC_LINE_SP_SNR_NEW Line-beam spiral detection in a cone ROI.

[detect, first_detect, first_encounter, effective_pulses] = ...
    MC_line_RA_snr_NEW(fasan_D, fasan_d, ...
    line_scan, f, omiga, UP, UV, init_beam_idx, R, jiaodu);
end
