function [detect, first_detect, first_encounter, effective_pulses] = ...
    MC_point_SP_snr_NEW(fasan_D, fasan_d, ...
    beam_vec, f, omiga, UP, UV, init_beam_idx, R, jiaodu)
%MC_POINT_SP_SNR_NEW Gaussian point-beam spiral detection in a cone ROI.

[detect, first_detect, first_encounter, effective_pulses] = ...
    MC_point_RA_snr_NEW(fasan_D, fasan_d, ...
    beam_vec, f, omiga, UP, UV, init_beam_idx, R, jiaodu);
end
