function [detect, first_detect, first_encounter, pulse_score] = ...
    MC_point_SP_snr_NEW(fasan_D, fasan_d, ...
    beam_vec, f, omiga, UP, UV, init_beam_idx, R, jiaodu, window_mode, mc_block_size)
%MC_POINT_SP_SNR_NEW Gaussian point-beam spiral detection in a cone ROI.

if nargin < 11 || isempty(window_mode)
    window_mode = 'variable';
end
if nargin < 12 || isempty(mc_block_size)
    mc_block_size = 100000;
end
validateattributes(mc_block_size, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'integer', 'positive'}, ...
    mfilename, 'mc_block_size');
[detect, first_detect, first_encounter, pulse_score] = ...
    MC_point_RA_snr_NEW(fasan_D, fasan_d, ...
    beam_vec, f, omiga, UP, UV, init_beam_idx, R, jiaodu, window_mode, mc_block_size);
end
