clc; clear; close all;

% Batch Monte Carlo entry point for cone-shaped ROI annular-beam scans.
N = 50000;
f = 5e3;
R = 2000;
JIAODU = 30;
fasan_D_LIST = 5e-3:5e-3:400e-3;
fasan_d = 1e-3;
v_min = 1;
v_max = 30;
omi_type = 'fast';

detect_R_RA = zeros(N, 1);
detect_R_SP = zeros(N, 1);
detect_L_RA = zeros(N, 1);
detect_L_SP = zeros(N, 1);
detect_P_RA = zeros(N, 1);
detect_P_SP = zeros(N, 1);
first_time_R_RA = zeros(N, 1);
first_time_R_SP = zeros(N, 1);
first_time_L_RA = zeros(N, 1);
first_time_L_SP = zeros(N, 1);
first_time_P_RA = zeros(N, 1);
first_time_P_SP = zeros(N, 1);
first_encounter_time_R_RA = nan(N, 1);
first_encounter_time_R_SP = nan(N, 1);
first_encounter_time_L_RA = nan(N, 1);
first_encounter_time_L_SP = nan(N, 1);
first_encounter_time_P_RA = nan(N, 1);
first_encounter_time_P_SP = nan(N, 1);
effective_pulses_R_RA = nan(N, 1);
effective_pulses_R_SP = nan(N, 1);
effective_pulses_L_RA = nan(N, 1);
effective_pulses_L_SP = nan(N, 1);
effective_pulses_P_RA = nan(N, 1);
effective_pulses_P_SP = nan(N, 1);

save_dir = fullfile(pwd, 'MC_ROI_RESULTS_SNR_NEW');
if ~exist(save_dir, 'dir')
    mkdir(save_dir);
end

for i = numel(fasan_D_LIST):-1:1
    fasan_D = fasan_D_LIST(i);

    % [detect_R_RA, first_time_R_RA, first_encounter_time_R_RA, ...
    %     effective_pulses_R_RA] = MC_func_ROI_NEW(R, N, f, ...
    %     JIAODU, 'ring', fasan_D, fasan_d, v_min, v_max, ...
    %     omi_type, 'raster');
    % 
    % save(fullfile(save_dir, ...
    %     ['MC_1par_ROI_NEW_RING_RA_D', num2str(fasan_D * 1000), ...
    %     'd', num2str(fasan_d * 1000), 'mrad.mat']), ...
    %     "detect_R_RA", "first_time_R_RA", ...
    %     "first_encounter_time_R_RA", "effective_pulses_R_RA");
    % 
    % [detect_R_SP, first_time_R_SP, first_encounter_time_R_SP, ...
    %     effective_pulses_R_SP] = MC_func_ROI_NEW(R, N, f, ...
    %     JIAODU, 'ring', fasan_D, fasan_d, v_min, v_max, ...
    %     omi_type, 'spiral');
    % 
    % save(fullfile(save_dir, ...
    %     ['MC_1par_ROI_NEW_RING_SP_D', num2str(fasan_D * 1000), ...
    %     'd', num2str(fasan_d * 1000), 'mrad.mat']), ...
    %     "detect_R_SP", "first_time_R_SP", ...
    %     "first_encounter_time_R_SP", "effective_pulses_R_SP");
    % 
    % [detect_L_RA, first_time_L_RA, first_encounter_time_L_RA, ...
    %     effective_pulses_L_RA] = MC_func_ROI_NEW(R, N, f, ...
    %     JIAODU, 'line', fasan_D, fasan_d, v_min, v_max, ...
    %     omi_type, 'raster');
    % 
    % save(fullfile(save_dir, ...
    %     ['MC_1par_ROI_NEW_LINE_RA_D', num2str(fasan_D * 1000), ...
    %     'd', num2str(fasan_d * 1000), 'mrad.mat']), ...
    %     "detect_L_RA", "first_time_L_RA", ...
    %     "first_encounter_time_L_RA", "effective_pulses_L_RA");
    % 
    % [detect_L_SP, first_time_L_SP, first_encounter_time_L_SP, ...
    %     effective_pulses_L_SP] = MC_func_ROI_NEW(R, N, f, ...
    %     JIAODU, 'line', fasan_D, fasan_d, v_min, v_max, ...
    %     omi_type, 'spiral');
    % 
    % save(fullfile(save_dir, ...
    %     ['MC_1par_ROI_NEW_LINE_SP_D', num2str(fasan_D * 1000), ...
    %     'd', num2str(fasan_d * 1000), 'mrad.mat']), ...
    %     "detect_L_SP", "first_time_L_SP", ...
    %     "first_encounter_time_L_SP", "effective_pulses_L_SP");

    [detect_P_RA, first_time_P_RA, first_encounter_time_P_RA, ...
        effective_pulses_P_RA] = MC_func_ROI_NEW(R, N, f, ...
        JIAODU, 'point', fasan_D, [], v_min, v_max, ...
        omi_type, 'raster');

    save(fullfile(save_dir, ...
        ['MC_1par_ROI_NEW_POINT_RA_D', num2str(fasan_D * 1000), ...
        'mrad.mat']), "detect_P_RA", "first_time_P_RA", ...
        "first_encounter_time_P_RA", "effective_pulses_P_RA");

    [detect_P_SP, first_time_P_SP, first_encounter_time_P_SP, ...
        effective_pulses_P_SP] = MC_func_ROI_NEW(R, N, f, ...
        JIAODU, 'point', fasan_D, [], v_min, v_max, ...
        omi_type, 'spiral');

    save(fullfile(save_dir, ...
        ['MC_1par_ROI_NEW_POINT_SP_D', num2str(fasan_D * 1000), ...
        'mrad.mat']), "detect_P_SP", "first_time_P_SP", ...
        "first_encounter_time_P_SP", "effective_pulses_P_SP");
end
