function cfg = ea_sens_default_config()
%EA_SENS_DEFAULT_CONFIG Configuration for standalone ROE sensitivity study.
%
% The module is intentionally independent of MC_EA.m and its helper files.
% All physical parameters are explicit so that sensitivity cases do not
% require edits to the existing simulation implementation.

moduleDir = fileparts(mfilename('fullpath'));

cfg = struct();
cfg.version = "1.0";
cfg.seed = 20260730;
cfg.screenN = 3000;
cfg.refineN = 3000;
cfg.bootstrapN = 200;
cfg.wDGrid_rad = [40, 60, 80, 100, 120, 150, 180, 220] * 1e-3;
cfg.refineWDGrid_rad = (40:10:220) * 1e-3;
cfg.timelyThresholds_s = [5, 10, 15];
cfg.targetProbabilities = [0.70, 0.80, 0.90];
cfg.primaryTimelyThreshold_s = 10;
cfg.primaryProbability = 0.80;
cfg.beamNames = ["line", "ring"];
cfg.outputRoot = moduleDir;
cfg.resultsDir = fullfile(moduleDir, "results");
cfg.figuresDir = fullfile(moduleDir, "figures");

cfg.execution = struct( ...
    "useParallel", true, ...
    "blockSize", 25000, ...
    "showProgress", true);

cfg.system = struct();
cfg.system.maxRange_m = 2000;
cfg.system.prf_Hz = 5000;
cfg.system.scanRate_rad_s = 2 * pi;
cfg.system.targetSpeed_m_s = 30;
cfg.system.beamWidth_rad = 0.8e-3;
cfg.system.pulseEnergy_J = 150e-6;
cfg.system.wavelength_m = 1550e-9;
cfg.system.receiverDiameter_m = 0.0508;
cfg.system.opticalTransmission = 0.80;
cfg.system.quantumEfficiency = 0.80;
cfg.system.rangeGate_s = 50e-9;
cfg.system.filterBandwidth_nm = 10;
cfg.system.darkCountRate_Hz = 400;
cfg.system.extinction_m_inv = 1.5e-5;
cfg.system.backscatter_m_inv_sr_inv = 0.3e-6;
cfg.system.skyRadiance_W_m2_sr_nm = 5e-9;
cfg.system.targetWidth_m = 0.30;
cfg.system.targetReflectivity = 0.50;
cfg.system.snrThreshold = 2;
cfg.system.gaussianCutoffWidths = 3;
cfg.system.targetSampleGrid = 7;
cfg.system.noiseLutStep_m = 0.5;

cfg.environment = struct( ...
    "nominalExtinction_m_inv", cfg.system.extinction_m_inv, ...
    "nominalBackscatter_m_inv_sr_inv", ...
        cfg.system.backscatter_m_inv_sr_inv, ...
    "nominalSkyRadiance_W_m2_sr_nm", ...
        cfg.system.skyRadiance_W_m2_sr_nm, ...
    "clearExtinctionScale", 0.5, ...
    "clearBackscatterScale", 0.5, ...
    "clearRadianceScale", 0.2, ...
    "adverseExtinctionScale", 2.0, ...
    "adverseBackscatterScale", 2.0, ...
    "adverseRadianceScale", 10.0);

cfg.factors = [ ...
    makeFactor("maxRange", "Maximum range", "maxRange_m", ...
        1500, 2500, "m"), ...
    makeFactor("targetSpeed", "Target speed", "targetSpeed_m_s", ...
        15, 45, "m/s"), ...
    makeFactor("prf", "Pulse repetition frequency", "prf_Hz", ...
        2500, 10000, "Hz"), ...
    makeFactor("scanRate", "Scan angular speed", "scanRate_rad_s", ...
        pi / 2, 2 * pi, "rad/s"), ...
    makeFactor("beamWidth", "Beam width", "beamWidth_rad", ...
        0.5e-3, 1.1e-3, "rad"), ...
    makeFactor("pulseEnergy", "Single-pulse energy", "pulseEnergy_J", ...
        100e-6, 200e-6, "J"), ...
    makeFactor("targetWidth", "Target width", "targetWidth_m", ...
        0.20, 0.40, "m"), ...
    makeFactor("reflectivity", "Target reflectivity", ...
        "targetReflectivity", 0.30, 0.70, "1"), ...
    makeFactor("environment", "Environment severity", ...
        "environmentSeverity", -1, 1, "index")];
end

function factor = makeFactor(name, label, key, lowValue, highValue, unit)
factor = struct( ...
    "name", string(name), ...
    "label", string(label), ...
    "key", string(key), ...
    "lowValue", lowValue, ...
    "highValue", highValue, ...
    "unit", string(unit));
end
