%RUN_EA_SENSITIVITY_PREVIEW Generate a quick, non-publication preview.
%
% This script executes the complete sensitivity workflow in smoke mode.
% The resulting figure is intended only for checking layout and data flow.

moduleDir = fileparts(mfilename("fullpath"));
addpath(moduleDir);
previewRoot = fullfile(moduleDir, "preview_output");

outputs = run_ea_sensitivity_analysis( ...
    "Mode", "smoke", ...
    "OutputRoot", previewRoot, ...
    "UseParallel", false, ...
    "Force", true, ...
    "BootstrapN", 10);

fprintf("Preview complete: %s\n", ...
    fullfile(previewRoot, "figures", "ea_sensitivity_main.png"));
fprintf("Screen rows: %d; refined rows: %d; interaction rows: %d\n", ...
    height(outputs.screenSummary), ...
    height(outputs.refineSummary), ...
    height(outputs.interactionSummary));
