function reportFile = ea_tornado_write_report(outputDirectory)
%EA_TORNADO_WRITE_REPORT Write bilingual method, caption, and result notes.

arguments
    outputDirectory (1,1) string
end

saved = load(fullfile(outputDirectory, "ea_tornado_analysis.mat"), ...
    "analysis");
analysis = saved.analysis;
cfg = analysis.design.config;
effects = analysis.effects;
reportFile = fullfile(outputDirectory, "methodology_and_results.md");
lines = [ ...
    "# EA 模式参数敏感度龙卷风分析 / EA Tornado Sensitivity"; ""; ...
    "## 方法"; ""; ...
    "线形与环形光束使用共同的 " + cfg.N + ...
        " 个运动目标、速度方向和扫描初相位。四个参数分别在基准的 " + ...
        "0.8、0.9、1.0、1.1 和 1.2 倍取值，其他参数保持不变。" + ...
        "最小合格角宽定义为 " + cfg.deadline_s + ...
        " s 内检出比例首次达到 " + 100 * cfg.requiredProbability + ...
        "% 的角宽，并仅在实际相邻角宽点之间线性插值；" + ...
        "不平滑、不施加单调包络、不外推。"; ""; ...
    "主响应为 `kappa = wD_ring_min / wD_line_min`。采用 " + ...
        analysis.options.Replicates + " 次共同索引的配对 bootstrap；" + ...
        "只有双光束可达率不低于 " + 100 * cfg.feasibilityThreshold + ...
        "% 时才报告 95% 区间。"; ""; ...
    "## 定量摘要"; ""; ...
    "- 基准 κ：" + numberOrNA(analysis.baselineKappa, "%.4f") + ...
        "（95%区间 " + intervalOrNA(analysis.baselineKappaCI) + "）。"];
for rowIndex = 1:height(effects)
    row = effects(rowIndex, :);
    lines(end + 1) = "- 排名 " + row.Rank + "，" + row.FactorLabel + ... %#ok<AGROW>
        "：−20% κ=" + numberOrNA(row.LowKappa, "%.4f") + ...
        "，+20% κ=" + numberOrNA(row.HighKappa, "%.4f") + ...
        "，龙卷风跨度=" + numberOrNA(row.TornadoSpan, "%.4f") + ...
        "，中间水平越界=" + ...
        string(row.IntermediateOutsideEndpointRange) + "。";
end
lines = [lines; ""; "## English method and caption"; ""; ...
    "The line and annular beams shared the same " + cfg.N + ...
        " moving targets, velocity directions, and scan phases. Pulse energy, " + ...
        "reflectivity, target speed, and atmospheric extinction were varied " + ...
        "one at a time from 80% to 120% of their baselines. Required divergence " + ...
        "was the first raw crossing of P_D(" + cfg.deadline_s + " s) >= " + ...
        100 * cfg.requiredProbability + ...
        "%, interpolated only between adjacent simulated widths. No smoothing, " + ...
        "monotone envelope, or extrapolation was applied. Uncertainty used " + ...
        analysis.options.Replicates + " paired bootstrap resamples."; ""; ...
    "**Figure caption.** Local one-at-a-time parameter sensitivity of the " + ...
        "annular-to-line required-divergence ratio in EA surveillance. Horizontal " + ...
        "bars cover the responses at -20%, baseline, and +20%; blue and orange " + ...
        "symbols mark the two endpoints. Whiskers are pointwise 95% paired-bootstrap " + ...
        "intervals. The solid vertical line and shaded band denote the common " + ...
        "baseline estimate and interval; the dashed line marks kappa=1. Smaller " + ...
        "kappa indicates a stronger annular angular-width advantage. Plus symbols " + ...
        "show the +/-10% audit levels."; ""; ...
    "This is a local four-factor OAT analysis over the stated +/-20% ranges. " + ...
        "It is not a Sobol decomposition, a joint-perturbation probability " + ...
        "statement, or evidence for ROI modes."];
writelines(lines, reportFile, Encoding="UTF-8");
end

function textValue = numberOrNA(value, format)
if isfinite(value)
    textValue = string(sprintf(format, value));
else
    textValue = "NA";
end
end

function textValue = intervalOrNA(interval)
if all(isfinite(interval))
    textValue = sprintf("%.4f–%.4f", interval(1), interval(2));
else
    textValue = "NA";
end
end
