function cfg = sens_default_config()
%SENS_DEFAULT_CONFIG Configuration for the standalone ROI sensitivity study.
%
% All values mirror the current manuscript model unless explicitly varied.
% Existing simulation files are not called or modified by this module.

moduleDir = fileparts(mfilename('fullpath'));

cfg = struct();
cfg.version = "1.0";
cfg.seed = 20260719;
cfg.screenN = 3000;
cfg.refineN = 10000;
cfg.bootstrapN = 1000;
cfg.timelyThreshold_s = 5;
cfg.trajectories = ["RA", "SP"];
cfg.outputRoot = moduleDir;
cfg.resultsDir = fullfile(moduleDir, 'results');
cfg.figuresDir = fullfile(moduleDir, 'figures');

cfg.execution = struct( ...
    'useParallel', true, ...
    'blockSize', 100000, ...
    'showProgress', true);

cfg.system = struct();
cfg.system.maxRange_m = 2000;
cfg.system.roiHalfAngle_deg = 30;
cfg.system.prf_Hz = 5000;
cfg.system.scanRate_rad_s = 2 * pi;
cfg.system.targetSpeed_m_s = 30;
cfg.system.pulseEnergy_J = 150e-6;
cfg.system.wavelength_m = 1550e-9;
cfg.system.receiverDiameter_m = 0.0508;
cfg.system.opticalTransmission = 0.80;
cfg.system.quantumEfficiency = 0.80;
cfg.system.rangeGate_s = 50e-9;
cfg.system.filterBandwidth_nm = 10;
cfg.system.darkCountRate_Hz = 400;
cfg.system.extinction_m_inv = 1.5e-5;
cfg.system.backscatter_m_inv_sr_inv = 0.3e-6;
cfg.system.skyRadiance_W_m2_sr_nm = 5e-9;
cfg.system.targetWidth_m = 0.30;
cfg.system.targetReflectivity = 0.50;
cfg.system.snrThreshold = 2;
cfg.system.gaussianCutoffWidths = 3;
cfg.system.targetSampleGrid = 7;
cfg.system.minimumEntryRange_m = 100;
cfg.system.noiseLutStep_m = 0.5;

cfg.beams = struct( ...
    'name', {"point", "line", "ring"}, ...
    'label', {"Spot", "Line", "Annular"}, ...
    'wD_rad', {20e-3, 180e-3, 150e-3}, ...
    'wd_rad', {NaN, 0.8e-3, 0.8e-3});

cfg.environment = struct( ...
    'lowSeverity', -1, ...
    'nominalSeverity', 0, ...
    'highSeverity', 1, ...
    'clearExtinctionScale', 0.5, ...
    'clearBackscatterScale', 0.5, ...
    'clearRadianceScale', 0.2, ...
    'adverseExtinctionScale', 2.0, ...
    'adverseBackscatterScale', 2.0, ...
    'adverseRadianceScale', 10.0);

cfg.factors = [ ...
    makeFactor("maxRange", "Maximum range", "maxRange_m", 1500, 2500, "m"), ...
    makeFactor("targetSpeed", "Target speed", "targetSpeed_m_s", 15, 45, "m/s"), ...
    makeFactor("roiHalfAngle", "ROI half-angle", "roiHalfAngle_deg", 20, 40, "deg"), ...
    makeFactor("scanRate", "Scan angular speed", "scanRate_rad_s", pi/2, 2*pi, "rad/s"), ...
    makeFactor("prf", "Pulse repetition frequency", "prf_Hz", 2500, 10000, "Hz"), ...
    makeFactor("beamWidth", "Beam width", "beamWidth_rad", 0.5e-3, 1.1e-3, "rad"), ...
    makeFactor("pulseEnergy", "Single-pulse energy", "pulseEnergy_J", 100e-6, 200e-6, "J"), ...
    makeFactor("targetWidth", "Target width", "targetWidth_m", 0.20, 0.40, "m"), ...
    makeFactor("reflectivity", "Target reflectivity", "targetReflectivity", 0.30, 0.70, "1"), ...
    makeFactor("snrThreshold", "SNR threshold", "snrThreshold", 1.5, 2.5, "1"), ...
    makeFactor("environment", "Environment severity", "environmentSeverity", -1, 1, "index")];

cfg.validation = struct( ...
    'probabilityAbsTolerance', 0.02, ...
    'warningTimeRelativeTolerance', 0.10, ...
    'referenceSummaryFile', fullfile(fileparts(moduleDir), ...
        'MC_ROI_RESULTS_SNR_NEW', 'roi_new_latest_line_ring_fasan_D_summary.csv'));
end

function factor = makeFactor(name, label, key, lowValue, highValue, unit)
factor = struct( ...
    'name', string(name), ...
    'label', string(label), ...
    'key', string(key), ...
    'lowValue', lowValue, ...
    'highValue', highValue, ...
    'unit', string(unit));
end
